[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200

lib_deps =
  wayoda/LedControl@^1.0.6
  majicdesigns/MD_MAX72XX@^3.5.1
  majicdesigns/MD_Parola@^3.7.3
